name: Run project Tests
on:
  pull_request: {}
  push: { branches: [ main ] }
jobs:  
  testAllModes: # Job 1
    name: ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    timeout-minutes: 5 # By default timeout is 360 minutes, but this repository is small
    strategy:
      fail-fast: false
      matrix:
        projectPath: [test-project]
        testMode: [playmode, editmode]
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v3
        with:
          lfs: true
          clean: true
          submodules: true
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}